{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 2, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 100.0, 100.0, 980.0, 560.0 ],
		"openinpresentation": 1,
		"presentation_rect": [ 0.0, 0.0, 940.0, 170.0 ],
		"boxes": [
			{ "box": { "id": "obj-1", "maxclass": "newobj", "text": "live.thisdevice",
				"numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ],
				"patching_rect": [ 30.0, 30.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-2", "maxclass": "newobj", "text": "js live-bridge.js",
				"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
				"patching_rect": [ 30.0, 120.0, 100.0, 22.0 ] } },
			{ "box": { "id": "obj-3", "maxclass": "newobj", "text": "node.script live-link.js @autostart 1",
				"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
				"patching_rect": [ 30.0, 210.0, 220.0, 22.0 ] } },
			{ "box": { "id": "obj-4", "maxclass": "newobj", "text": "route stage",
				"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
				"patching_rect": [ 300.0, 260.0, 80.0, 22.0 ] } },
			{ "box": { "id": "obj-5", "maxclass": "live.drag",
				"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
				"patching_rect": [ 300.0, 310.0, 100.0, 45.0 ],
				"presentation": 1, "presentation_rect": [ 848.0, 40.0, 86.0, 100.0 ],
				"saved_attribute_attributes": { "valueof": { "parameter_invisible": 1, "parameter_longname": "live.drag", "parameter_shortname": "live.drag", "parameter_type": 3 } },
				"varname": "live.drag" } },
			{ "box": { "id": "obj-6", "maxclass": "textbutton", "text": "Expand ⇱",
				"numinlets": 1, "numoutlets": 3, "outlettype": [ "", "", "int" ],
				"patching_rect": [ 620.0, 30.0, 100.0, 26.0 ],
				"presentation": 1, "presentation_rect": [ 848.0, 8.0, 86.0, 26.0 ],
				"parameter_enable": 0 } },
			{ "box": { "id": "obj-7", "maxclass": "message", "text": "front",
				"numinlets": 2, "numoutlets": 1, "outlettype": [ "" ],
				"patching_rect": [ 620.0, 70.0, 45.0, 22.0 ] } },
			{ "box": { "id": "obj-8", "maxclass": "comment", "text": "drag →",
				"numinlets": 1, "numoutlets": 0,
				"patching_rect": [ 300.0, 360.0, 60.0, 20.0 ],
				"presentation": 1, "presentation_rect": [ 848.0, 142.0, 86.0, 18.0 ] } },
			{ "box": { "id": "obj-9", "maxclass": "newobj", "text": "plugin~",
				"numinlets": 1, "numoutlets": 2, "outlettype": [ "signal", "signal" ],
				"patching_rect": [ 850.0, 420.0, 55.0, 22.0 ] } },
			{ "box": { "id": "obj-10", "maxclass": "newobj", "text": "plugout~",
				"numinlets": 2, "numoutlets": 2, "outlettype": [ "signal", "signal" ],
				"patching_rect": [ 850.0, 470.0, 62.0, 22.0 ] } },
			{ "box": { "id": "obj-11", "maxclass": "newobj", "text": "del 1200",
				"numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ],
				"patching_rect": [ 430.0, 80.0, 60.0, 22.0 ] } },
			{ "box": { "id": "obj-12", "maxclass": "message", "text": "url http://127.0.0.1:8765/?strip=1",
				"numinlets": 2, "numoutlets": 1, "outlettype": [ "" ],
				"patching_rect": [ 430.0, 120.0, 200.0, 22.0 ] } },
			{ "box": { "id": "obj-15", "maxclass": "newobj", "text": "del 2500",
				"numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ],
				"patching_rect": [ 620.0, 200.0, 60.0, 22.0 ] } },
			{ "box": { "id": "obj-13", "maxclass": "jweb",
				"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
				"patching_rect": [ 430.0, 160.0, 380.0, 90.0 ],
				"presentation": 1, "presentation_rect": [ 4.0, 4.0, 838.0, 162.0 ] } },
			{ "box": {
				"id": "obj-14", "maxclass": "newobj", "text": "p sidebar",
				"numinlets": 1, "numoutlets": 0,
				"patching_rect": [ 620.0, 110.0, 70.0, 22.0 ],
				"patcher": {
					"fileversion": 1,
					"appversion": { "major": 8, "minor": 2, "revision": 0, "architecture": "x64", "modernui": 1 },
					"classnamespace": "box",
					"rect": [ 1000.0, 60.0, 540.0, 1000.0 ],
					"openinpresentation": 1,
					"presentation_rect": [ 0.0, 0.0, 520.0, 960.0 ],
					"boxes": [
						{ "box": { "id": "obj-1", "maxclass": "inlet",
							"numinlets": 0, "numoutlets": 1, "outlettype": [ "" ],
							"patching_rect": [ 20.0, 20.0, 30.0, 30.0 ] } },
						{ "box": { "id": "obj-2", "maxclass": "newobj", "text": "thispatcher",
							"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
							"patching_rect": [ 20.0, 160.0, 80.0, 22.0 ] } },
						{ "box": { "id": "obj-3", "maxclass": "newobj", "text": "loadbang",
							"numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ],
							"patching_rect": [ 130.0, 20.0, 60.0, 22.0 ] } },
						{ "box": { "id": "obj-4", "maxclass": "message",
							"text": "window flags float, window flags nomenu, window title Backline, window size 1000 60 1520 1020",
							"numinlets": 2, "numoutlets": 1, "outlettype": [ "" ],
							"patching_rect": [ 130.0, 60.0, 420.0, 22.0 ] } },
						{ "box": { "id": "obj-5", "maxclass": "jweb",
							"numinlets": 1, "numoutlets": 2, "outlettype": [ "", "" ],
							"patching_rect": [ 20.0, 220.0, 480.0, 700.0 ],
							"presentation": 1, "presentation_rect": [ 0.0, 0.0, 520.0, 960.0 ] } },
						{ "box": { "id": "obj-6", "maxclass": "newobj", "text": "del 1500",
							"numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ],
							"patching_rect": [ 300.0, 100.0, 60.0, 22.0 ] } },
						{ "box": { "id": "obj-7", "maxclass": "message", "text": "url http://127.0.0.1:8765/",
							"numinlets": 2, "numoutlets": 1, "outlettype": [ "" ],
							"patching_rect": [ 300.0, 140.0, 170.0, 22.0 ] } }
					],
					"lines": [
						{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-2", 0 ] } },
						{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-4", 0 ] } },
						{ "patchline": { "source": [ "obj-4", 0 ], "destination": [ "obj-2", 0 ] } },
						{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-6", 0 ] } },
						{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-7", 0 ] } },
						{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-5", 0 ] } }
					]
				},
				"saved_object_attributes": { "description": "", "digest": "", "globalpatchername": "", "tags": "" } } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-2", 0 ] } },
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-11", 0 ] } },
			{ "patchline": { "source": [ "obj-1", 0 ], "destination": [ "obj-15", 0 ] } },
			{ "patchline": { "source": [ "obj-15", 0 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-11", 0 ], "destination": [ "obj-12", 0 ] } },
			{ "patchline": { "source": [ "obj-12", 0 ], "destination": [ "obj-13", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 0 ], "destination": [ "obj-3", 0 ] } },
			{ "patchline": { "source": [ "obj-2", 1 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-3", 0 ], "destination": [ "obj-4", 0 ] } },
			{ "patchline": { "source": [ "obj-4", 0 ], "destination": [ "obj-5", 0 ] } },
			{ "patchline": { "source": [ "obj-4", 1 ], "destination": [ "obj-2", 0 ] } },
			{ "patchline": { "source": [ "obj-6", 0 ], "destination": [ "obj-7", 0 ] } },
			{ "patchline": { "source": [ "obj-7", 0 ], "destination": [ "obj-14", 0 ] } },
			{ "patchline": { "source": [ "obj-9", 0 ], "destination": [ "obj-10", 0 ] } },
			{ "patchline": { "source": [ "obj-9", 1 ], "destination": [ "obj-10", 1 ] } }
		]
	}
}
